# Generated by Django 2.1.1 on 2018-11-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trabajos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
