# Generated by Django 2.1.1 on 2018-11-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='articulo',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
