# Generated by Django 2.1.1 on 2018-11-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0002_auto_20181129_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='image',
            field=models.ImageField(upload_to='Articulos'),
        ),
    ]
