# Generated by Django 2.1.1 on 2018-11-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0003_auto_20181129_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Direccionar a otro sitio'),
        ),
    ]
